version: '3.1'
services:
  stats-server:
    build: ./stat-service/server
    image: server:latest
    container_name: ewm_stat_server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - STAT_DB=stat_db
      - STAT_DB_HOST=ewm_stat_db
      - STAT_DB_PORT=5432
      - STAT_USER=ewm
      - STAT_PASSWORD=ewm

  stats-db:
    image: postgres:14-alpine
    container_name: ewm_stat_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  ewm-service:
    build: ./main-service
    image: main-service:latest
    container_name: ewm_main_service
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - MAIN_DB=main_db
      - MAIN_DB_HOST=ewm_main_db
      - MAIN_DB_PORT=5432
      - MAIN_USER=ewm
      - MAIN_PASSWORD=ewm
      - STAT_SERVER_URL=http://ewm_stat_server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_main_db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
